# Generated by Django 4.0.2 on 2022-02-07 04:55

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.TextField(default='')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='main_category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('preptime', models.TextField(max_length=50)),
                ('tags', models.TextField(default='')),
                ('ingredients', models.TextField(default='')),
                ('instructions', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('calories', models.TextField(default='')),
                ('carbs', models.TextField(default='')),
                ('sod', models.TextField(default='')),
                ('cho', models.TextField(default='')),
                ('fat', models.TextField(default='')),
                ('pro', models.TextField(default='')),
                ('created_by', models.CharField(default='', max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
