# Generated by Django 4.0.2 on 2022-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recipes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.TextField(max_length=150),
        ),
    ]
