# Generated by Django 4.0.2 on 2022-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recently_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
