# Generated by Django 4.0.3 on 2022-04-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rating_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratings',
            field=models.FloatField(),
        ),
    ]
