# Generated by Django 4.0.2 on 2022-03-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysname',
            name='days',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
