# Generated by Django 4.0.2 on 2022-03-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_daysname_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='selfnote',
        ),
    ]
