# Generated by Django 4.0.2 on 2022-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_mealplan_selfnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysname',
            name='days',
            field=models.CharField(max_length=100),
        ),
    ]
