# Generated by Django 4.0.2 on 2022-03-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipes_recently_viewed'),
        ('planner', '0004_alter_daysname_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='recipe',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipeplan',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='recipeplan', to='main.Recipes'),
        ),
    ]
