# Generated by Django 4.0.2 on 2022-03-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipes_recently_viewed'),
        ('planner', '0005_remove_mealplan_recipe_mealplan_recipeplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='recipeplan',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recipes'),
        ),
    ]
