# Generated by Django 4.0.2 on 2022-03-10 14:06

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_mealplan_recipeplan_mealplan_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysname',
            name='day_slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='days'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plandays', to='planner.daysname'),
        ),
    ]
