# Generated by Django 4.0.2 on 2022-03-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_daysname_day_slug_alter_mealplan_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysname',
            old_name='day_slug',
            new_name='slug',
        ),
    ]
