# Generated by Django 4.0.2 on 2022-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_rename_day_slug_daysname_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysname',
            name='slug',
            field=models.SlugField(),
        ),
    ]
